### ISSUE TITLE
request: 

### ISSUE THREAD

**Issue by Fosi123** [rxri/spicetify-extensions#1]
### 📦 Extension name

adblockify

### 📝 Provide a description of the new feature

Hello,c an you make it possible for us to see Spotify lyrics without having premium?

**Comment by rxri** [comment]
Hey, not really since that’s technically not possible. You can use `lyrics-plus` custom app instead:
`spicetify config custom_apps lyrics-plus` and `spicetify apply`

**Comment by RoverBot-Dev** [comment]
![image](https://github.com/rxri/spicetify-extensions/assets/68994821/4b6d99fa-c254-48db-8128-1b5936d562cc)
after disabling this checkbox in experimental settings (click on your profile image on top right to go there) the lyrics seem to work fine without premium 🤔 wanted to point this out
