### ISSUE TITLE
bug: AdBlock not working

### ISSUE THREAD

**Issue by rusty-man** [rxri/spicetify-extensions#10]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.41
- Spicetify version: 2.36.14
windows
```

### 📦 Extension name

adblock

### 📝 Description

Adblock doesn't work after i updated spicetify to version 2.36.14
I reinstalled the extension just to make sure, and it still isnt working.

Not sure about the ads itself, but i can see the banners when i open spotify.

**Comment by rxri** [comment]
You do not have latest spicetify applied then. `spicetify restore backup apply`.
