### ISSUE TITLE
bug: Issue with extensions not working even after reinstallation.

### ISSUE THREAD

**Issue by heylowthere** [rxri/spicetify-extensions#11]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:
- Spicetify version:
```

### 📦 Extension name

adblock,beautiful lyrics

### 📝 Description

Have installed spotify from installer (not from microsoft store) and installed the adblocker and beautiful lyrics extensions, they are not working. Have tried uninstalling and reinstalling the extensions multiple times, still don't work.

**Comment by rxri** [comment]
Beautiful Lyrics is not my extension. Also you did not provide spotify version and spicetify version. Won't help until you fill out the issue template.
