### ISSUE TITLE
bug: AdBlock not working

### ISSUE THREAD

**Issue by GreenBlockBuster** [rxri/spicetify-extensions#12]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:Latest
- Spicetify version:Latest
```

### 📦 Extension name

AdBlock

### 📝 Description

after the install, ads remain, install from the marketplace 

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/1816735a-670d-46cd-87ad-f846d7e8ea5d)

**Comment by GreenBlockBuster** [comment]
Help

**Comment by rxri** [comment]
https://github.com/rxri/spicetify-extensions/issues/13#issuecomment-2232919057 also "latest" doesn't exist

**Comment by rxri** [comment]
Btw you clearly have Spicetify icon on the topbar indicating that update is available. If CLI says it's up to date, run `spicetify restore backup apply`
