### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by lkwsalat** [rxri/spicetify-extensions#13]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:
- Spicetify version:1.0.2
```

### 📦 Extension name

adblocker

### 📝 Description

the adblocker didnt work

**Comment by rxri** [comment]
Not filled out template. Spicetify version that you gave is marketplace's. Adblockify works just fine. Update spicetify if update is necessary
