### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by sachinchaudhary1808** [rxri/spicetify-extensions#15]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
can my spotify acc get banned if i use adblock ?
```

### 📦 Extension name

adblock

### 📝 Description

meh

### 📸 Screenshots

 bleh

**Comment by rxri** [comment]
You won't

**Comment by sachinchaudhary1808** [comment]
> You won't

U mean it will not get banned?

**Comment by rxri** [comment]
> > You won't
> 
> U mean it will not get banned?

That's what I said, yes.

**Comment by sachinchaudhary1808** [comment]
Say yes or no, will my account get banned if i use adblock extension?

**Comment by rxri** [comment]
> Say yes or no, will my account get banned if i use adblock extension?

https://github.com/rxri/spicetify-extensions/issues/15#issuecomment-2265585140

**Comment by sachinchaudhary1808** [comment]
> > Say yes or no, will my account get banned if i use adblock extension?
> 
> https://github.com/rxri/spicetify-extensions/issues/15#issuecomment-2265585140

Okay now i get the meaning, my english is not that great, thanks
