### ISSUE TITLE
bug: seeing ads  

### ISSUE THREAD

**Issue by sachinchaudhary1808** [rxri/spicetify-extensions#16]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.42.290.g242057a2
- Spicetify version:i use a nix flake and recently updated the flake, https://github.com/Gerg-L/spicetify-nix
```

### 📦 Extension name

adblock

### 📝 Description

seeing ads 

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/5072d460-6542-43ec-a1e2-a3d49487d185)

**Comment by sachinchaudhary1808** [comment]
https://github.com/Gerg-L/spicetify-nix/blob/5a4a301de746e16851165b0da8ab6d38ed37b8dd/pkgs/extensions.nix#L149

this is what i found

**Comment by rxri** [comment]
Should be okay now. Spotify with every new version takes longer to load, causing experimental features to not be changed. Made a fallback plus am setting it with a little of the timeout right now

**Comment by sachinchaudhary1808** [comment]
> Should be okay now. Spotify with every new version takes longer to load, causing experimental features to not be changed. Made a fallback plus am setting it with a little of the timeout right now


Thanks

**Comment by sachinchaudhary1808** [comment]
> Should be okay now. Spotify with every new version takes longer to load, causing experimental features to not be changed. Made a fallback plus am setting it with a little of the timeout right now

is it solved by now ? i still see those ads

**Comment by sachinchaudhary1808** [comment]
or may be he need to update the flake ?

**Comment by rxri** [comment]
> or may be he need to update the flake ?, i will see after he updates the flake

Bot will update the flake as far as I am aware

**Comment by sachinchaudhary1808** [comment]
> > or may be he need to update the flake ?, i will see after he updates the flake
> 
> Bot will update the flake as far as I am aware

Thanks

**Comment by sachinchaudhary1808** [comment]
> > or may be he need to update the flake ?, i will see after he updates the flake
> 
> Bot will update the flake as far as I am aware

hey i still see ads why ?
