### ISSUE TITLE
bug: adblock is not working again 

### ISSUE THREAD

**Issue by sachinchaudhary1808** [rxri/spicetify-extensions#17]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.42.290.g242057a2
- Spicetify version:flake of https://github.com/Gerg-L/spicetify-nix/blob/5a4a301de746e16851165b0da8ab6d38ed37b8dd/pkgs/extensions.nix#L149
```

### 📦 Extension name

adblock

### 📝 Description

not working still

### 📸 Screenshots

i don't have one for now

**Comment by sachinchaudhary1808** [comment]
![image](https://github.com/user-attachments/assets/82112499-f427-4636-bff9-34cf0c14051e)

**Comment by rxri** [comment]
You're not on latest version then. It changes the experimental feature because I can see that so the issue is in your end

**Comment by sachinchaudhary1808** [comment]
> You're not on latest version then. It changes the experimental feature because I can see that so the issue is in your end

i don't think i can get more latest version then that

**Comment by rxri** [comment]
![image](https://github.com/user-attachments/assets/7009cb3f-f869-4054-a0ed-de21d336fc9f)
read means it's in override state which is set to `false`. It works just fine. I'm pretty sure you're not on latest then. I already know that the adblock extension doesn't even load because you have `Explore Premium` button in the topbar which should disappear.

**Comment by sachinchaudhary1808** [comment]
> ![image](https://private-user-images.githubusercontent.com/9348108/356813513-7009cb3f-f869-4054-a0ed-de21d336fc9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMDkxMjMsIm5iZiI6MTcyMzMwODgyMywicGF0aCI6Ii85MzQ4MTA4LzM1NjgxMzUxMy03MDA5Y2IzZi1mODY5LTQwNTQtYTBlZC1kZTIxZDMzNmZjOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTY1MzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDU4YTI4ZjRlYmYzZjgyZTBlZDEyZjliMTYyODU4YTI5MzljYjJkNGU5ODA5ZTQxNzJmYzk1MzA2NTM0OGU0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jeHpBvWyCqfb8IdhI1QM63al7BLcHZox-huLcRIEBWU) Red means it's in override state which is set to `false`. It works just fine. I'm pretty sure you're not on latest then. I already know that the adblock extension doesn't even load for you because you have `Explore Premium` button in the topbar which should disappear.

i'm on nixos unstable may be nixos dont have latest spotify version

**Comment by rxri** [comment]
> i'm on nixos unstable may be nixos dont have latest spotify version

Why would it matter? This extension works on many spotify versions. I'm saying that you do not have adblock applied to spotify, at all.

**Comment by sachinchaudhary1808** [comment]
> > i'm on nixos unstable may be nixos dont have latest spotify version
> 
> Why would it matter? This extension works on many spotify versions. I'm saying that you do not have adblock applied to spotify, at all.

but i have this is my config 
```
{ config, pkgs, inputs, ... }: {
  programs.spicetify =
    let spicePkgs = inputs.spicetify-nix.legacyPackages.${pkgs.system};
    in {
      enable = true;
      enabledExtensions = with spicePkgs.extensions; [
        adblock
        lastfm
        fullAppDisplay
        hidePodcasts
        betterGenres
        shuffle # shuffle+ (special characters are sanitized out of extension names)
      ];
      theme = spicePkgs.themes.catppuccin;
      colorScheme = "mocha";
    };
}
```

**Comment by rxri** [comment]
I don't know anything about nix packages and how they work. I'm just saying that it doesn't load for you

**Comment by sachinchaudhary1808** [comment]
> I don't know anything about nix packages and how they work. I'm just saying that it doesn't load for you

sad
