### ISSUE TITLE
bug: Shuffle button not working after latest adblock.js commit

### ISSUE THREAD

**Issue by Elidon007** [rxri/spicetify-extensions#18]
### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.42.290 from Flathub
- Spicetify version: 2.37.1
```

### 📦 Extension name

adblock

### 📝 Description

To reproduce this error I have to install the adblock.js file from Aug 7, 2024.
The shuffle button doesn't change the shuffle state, and I expect it to change between no shuffle, shuffle, and smart shuffle.
When the extension is removed I don't observe the bug.
A solution I found was reverting to the adblock.js commit from Jul 18, 2024, which fixes all issues for me.
Therefore I suspect that this is a problem with the latest commit that should be fixed.

**Comment by rxri** [comment]
That's not the fault of adblock. It's just a visual bug. I will disable smart shuffle completely anyways.
