### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by emmaphoto** [rxri/spicetify-extensions#20]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.44.405.g81fd6352

- Spicetify version:v2.37.1
```

### 📦 Extension name

adblockify

### 📝 Description

adverts are back above the player

**Comment by rxri** [comment]
Can't reproduce. If still happens after spotify restart, install it locally.
