### ISSUE TITLE
bug: adblockify does not work

### ISSUE THREAD

**Issue by Criptonized** [rxri/spicetify-extensions#21]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.44.405
- Spicetify version: 2.37.4
```

### 📦 Extension name

adblockify

### 📝 Description

ad blocka not working update it pls

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/1c9604a1-971a-4621-9202-1f0c6df9879a)

**Comment by AnonymousGryffindor** [comment]
![image](https://github.com/user-attachments/assets/932d30bd-4fda-4fbf-bf79-2c5b752d78c6)
the banner ads and ads between songs have resumed

**Comment by T0RNATO** [comment]
only now do I realise how insufferable spotify ads are. I would greatly appreciate a fix

**Comment by rxri** [comment]
Well, that's not really adblock's fault. Marketplace does not inject the extension for 99.99%. What I would recommend is to reinstall spotify, re-apply spicetify while on latest (v2.37.4) with `spicetify backup apply` and re-installing adblock from marketplace, or installing it locally.

**Comment by daqnxx** [comment]
same thing started happening to me today, i've tried to reinstall it and all but still not working

**Comment by rxri** [comment]
![image](https://github.com/user-attachments/assets/878718f4-3f9d-49a6-9d7c-79952e2f2a14)
Adblockify works just fine, as it should basically. When new ad is inserted into the slot, adblockify removes it. 

----------
```
Spotify for Windows (64 bit)
1.2.45.451.gac8a666f
Spicetify vDev
xpui_2024-08-23_1724395464028_ac8a666
cef_127.3.4+ge9e2e14+chromium-127.0.6533.100
Runtime: Chrome
Build System: Bazel
```

**Comment by rxri** [comment]
If you keep having ads then please follow these instructions:

1. Make sure you're on `v2.37.4` (latest spicetify version)
2. Please re-apply spicetify (`spicetify restore backup apply`)
3. If still doesn't work, remove `adblockify` from marketplace and add it again
4. If it doesn't help either, please reinstall spotify (uninstall and install it again)

If this doesn't work, please post your spotify version:

![image](https://github.com/user-attachments/assets/7537a9fb-dbc7-492b-b347-f9365f934e93)
![image](https://github.com/user-attachments/assets/553ff65b-f42f-4ccf-9ffd-9a3d1a788236)
Click on `Spicetify v<version>` to expand the data and then click the copy button on the right and post it here. Thank you.

**Comment by Coldmint25** [comment]
Hello I have already tried all the steps and it still doesn't work here is the version
Spotify for Windows (64 bit)
1.2.44.405.g81fd6352
Spicetify v2.37.4

**Comment by rxri** [comment]
At this point I think something is up with spicetify on 1.2.44. I will look into it later

**Comment by blindmodz** [comment]
For me wasnt working, reinstalled through marketplace and used `spicetify apply` on Terminal and started working again

**Comment by daqnxx** [comment]
Installing extension locally fixed the issue for me

**Comment by T0RNATO** [comment]
reinstalling in marketplace seems to have resolved this

**Comment by Nebroc351** [comment]
I tried the troubleshoot steps but cannot get it to work on 1.2.45, I will try to find an older spotify version to install for now

Spotify  pour Windows (64 bits)
1.2.45.454.gc16ec9f6
Spicetify v2.37.4
Theme: Hazy / Base
Extensions: adblock.js, autoSkipVideo.js, loopyLoop.js, shuffle+.js, trashbin.js, beautiful-lyrics.mjs, hidePodcasts.js, QueueTime.js, bookmark.js, songstats.js, writeify.js, quickQueue.js, made-for-you-shortcut.js, spotifyGenres.js, volumePercentage.js, remove-unplayable-songs.js, css-editor.js, hazy.js
Custom apps: marketplace, stats, name-that-tune

**Comment by rxri** [comment]
It's confirmed to be spicetify issue. You can downgrade to `2.37.1` for the time being if this did not fix it for you.
```
$v="2.37.1"; Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/spicetify/cli/main/install.ps1" | Invoke-Expression
```

**Comment by rxri** [comment]
`v2.37.5` should fix this issue.
