### ISSUE TITLE
bug: ad happened

### ISSUE THREAD

**Issue by morbiusfaust** [rxri/spicetify-extensions#25]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:
- Spicetify version:
```

### 📦 Extension name

ad block

### 📝 Description

I am finding that ad blocking is not working as intended. I have verified the settings in my browser, and they appear to be correct. However, I am still receiving advertisements. I have attempted to refresh the page, but this did not resolve the issue.

**Comment by rxri** [comment]
You did not fill the template with versions. Closing
