### ISSUE TITLE
bug: Ads appearing again

### ISSUE THREAD

**Issue by jacobcapper** [rxri/spicetify-extensions#28]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:Spotify for Windows (64 bit) 1.2.45.454.gc16ec9f6
- Spicetify v2.37.7
```

### 📦 Extension name

Adblockify

### 📝 Description

Ads have started appearing again

### 📸 Screenshots

![Capture](https://github.com/user-attachments/assets/babf5053-7bfe-42d1-a636-8fde0c1240b0)

**Comment by rxri** [comment]
https://github.com/rxri/spicetify-extensions/issues/21#issuecomment-2311167923
