### ISSUE TITLE
bug: adblock doesn't work

### ISSUE THREAD

**Issue by ChujekBoczek** [rxri/spicetify-extensions#29]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.47.364.gf06e5cee
- Spicetify version:v2.38.3
```

### 📦 Extension name

adblockify

### 📝 Description

even with adblockify mod, I still have ads. it's not the first time.

### 📸 Screenshots

![obraz_2024-10-03_183712676](https://github.com/user-attachments/assets/e13c4755-7307-478c-953e-d32edcae9c94)

**Comment by rxri** [comment]
Install it locally then, not via marketplace. also spicetify version is not latest.
