### ISSUE TITLE
bug: Found error in DevTools

### ISSUE THREAD

**Issue by vilewired** [rxri/spicetify-extensions#3]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1:1.2.31.1205-2
- Spicetify version: v2.36.11
```

### 📦 Extension name

adblock

### 📝 Description

Checked the DevTools for an issue with another extension, then noticed there have been +100k errors thrown since I started looking at the other extension.
I do not really know what this is, if you have a clue and you can fix this, that would of course be very awesome :)

### 📸 Screenshots

![image](https://cdn.vile.jp/img/20240518180758.png)
![image](https://cdn.vile.jp/img/20240518181025.png)

**Comment by rxri** [comment]
Seems like 1.2.31 doesn’t have this function. will need to look into it

**Comment by rxri** [comment]
Should be fixed!

**Comment by vilewired** [comment]
Yeah, seems like everything works well again, and thank you for the quick turnaround :3
