### ISSUE TITLE
bug: the ads still play when the adblok is installed

### ISSUE THREAD

**Issue by jailmanwee** [rxri/spicetify-extensions#31]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: the newest
- Spicetify version:newest
```

### 📦 Extension name

adblock

### 📝 Description

the adblock suddenkty stopped working

**Comment by rxri** [comment]
Not properly filled out template. I don't know what `latest` is.
