### ISSUE TITLE
request(adblockify): Allow Miniplayer resizing

### ISSUE THREAD

**Issue by i3vie** [rxri/spicetify-extensions#32]
### 📦 Extension name

Adblockify/Adblock

### 📝 Provide a description of the new feature

If possible, it would be nice to be able to resize the new Spotify miniplayer without Premium. A recent Spotify update has added this mini-player feature, that spawns a new window that can be dragged around independent of the main Spotify window:
![image](https://github.com/user-attachments/assets/eae869e1-7bc1-447e-bafd-2a4d000898d1)
But if you try to shrink it below its default size, it prompts you to get Premium:
![image](https://github.com/user-attachments/assets/2c63bb94-a9c1-4f43-85f7-cf482ca2434e)
(Pressing 'not now' resizes it back to its non-premium minimum size.)
It would be nice to have the option to resize the mini-player without having Premium.

**Comment by rxri** [comment]
Would require patching mini-player javascript file in xpui. Not possible in v2.
