### ISSUE TITLE
bug: Ad placeholder visible, sometimes displays ad

### ISSUE THREAD

**Issue by noidesserts** [rxri/spicetify-extensions#33]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.51.345.gcc39d911
- Spicetify version: 2.38.4
Windows 11 22H2 for x64-based Systems (KB5023706)
```

### 📦 Extension name

adblockify

### 📝 Description

Usual usage. Ad placeholder shows, and sometimes ad plays. Only UI ads, no video/audio ads.

Adblocker works on launch. but reload might mess it up a little.

### 📸 Screenshots

![Screenshot 2024-11-25 204056](https://github.com/user-attachments/assets/2c630125-c655-415a-97a1-16172fdf998b)

**Comment by rxri** [comment]
Means the css didn't load. I recommend installing adblockify locally.
