### ISSUE TITLE
bug: song stats not working

### ISSUE THREAD

**Issue by levanter4419** [rxri/spicetify-extensions#35]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.52.442
- Spicetify version: 2.38.5
```

### 📦 Extension name

song stats

### 📝 Description

I downloaded everything correctly but when I play a song and click on "View Song Stats" the popup window is just blank.

### 📸 Screenshots

<img width="438" alt="Screenshot 2024-12-08 at 11 06 07 AM" src="https://github.com/user-attachments/assets/727bc2dc-8b30-43f3-b295-e6258f6fe9cf">

**Comment by rxri** [comment]
Works just fine on my end. Reinstall or download it locally.
