### ISSUE TITLE
bug: the queue or song of the next doesn't play... 

### ISSUE THREAD

**Issue by yayyerplayz** [rxri/spicetify-extensions#36]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:
Spotify for macOS (Apple Silicon)
1.2.53.438.g246d60c9
Spicetify v2.38.7

- Spicetify version:
Spicetify v2.38.7
```

### 📦 Extension name

adblock

### 📝 Description

I'm unsure how to reproduce the error, but I saw on a reddit post that someone 2 days ago had the same issue with me. 
https://www.reddit.com/r/spicetify/comments/1hlbr3c/spotify_doesnt_go_to_the_next_song_after/ 
I hope this is fixed soon. 
But the first picture is the issue that the song when it's done, it doesn't go to the next in the playlist. The next song does not play after. 

### 📸 Screenshots

<img width="1469" alt="Screenshot 2024-12-26 at 9 30 17 PM" src="https://github.com/user-attachments/assets/f24c2ea5-89fe-4a97-921e-98797080f97f" />

<img width="1468" alt="Screenshot 2024-12-26 at 9 28 39 PM" src="https://github.com/user-attachments/assets/2562e18d-8e3e-4c02-a89b-853bd9af7ad5" />
After skipping or the song is done, the current song stays at the end second.

**Comment by rxri** [comment]
Spotify bug on 1.2.53. Downgrade.
