### ISSUE TITLE
bug: issue adding a song to queue

### ISSUE THREAD

**Issue by zzafkiell** [rxri/spicetify-extensions#37]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:spotify for windows (64bits) 1.2.53.438.g246d60c9
- Spicetify version:v2.38.7
```

### 📦 Extension name

adblockify

### 📝 Description

When you add a song to the queue, the next song does not play and is paused automatically. 
This will happen again and again unless you delete the queue.

**Comment by rxri** [comment]
Spotify 1.2.53 bug.
