### ISSUE TITLE
bug: popup ads still appear

### ISSUE THREAD

**Issue by WiLuX-Source** [rxri/spicetify-extensions#5]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.37.701
- Spicetify version: 2.36.11
```

### 📦 Extension name

adblockify

### 📝 Description

ad banner pops up with `ReactModalPortal`

**Comment by WiLuX-Source** [comment]
I will screenshot if I get banner again tomorrow.

**Comment by rxri** [comment]
Do you have the latest version of Adblock though? You may be cached via jsdelivr because it's not possible since we disable the thing they send these popups by

**Comment by WiLuX-Source** [comment]
![image](https://github.com/rxri/spicetify-extensions/assets/61833703/d9b0d8dd-ee61-4866-b5a5-7e2c5dd10f20)

**Comment by WiLuX-Source** [comment]
I installed through marketplace is there way to check adblock version as well?

**Comment by WiLuX-Source** [comment]
since I have devtools enabled I checked contents of adblock.js with mine and yours manually, yes they are same.

**Comment by Exinie** [comment]
Same issue for me as well.

**Comment by WiLuX-Source** [comment]
It will take a while, currently testing it and made sure it is not cached.

**Comment by rxri** [comment]
Will close in the morning if no one will report this issue anymore

**Comment by rxri** [comment]
Now it will work for 100% because it correctly overrides the exp feature (enableInAppMessages) that handles these popups inside ReactModalPortal. No need to keep this issue opened
