### ISSUE TITLE
bug: phrasetoplaylist is not working

### ISSUE THREAD

**Issue by JailbreakSuv** [rxri/spicetify-extensions#6]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.38.720
- Spicetify version: v2.36.11
```

### 📦 Extension name

PhraseToPlaylist

### 📝 Description

The playlist when any phrase is inputted is not working.

**Comment by rxri** [comment]
Yes. I know.
TODO file mentions it:
```
## Phrase to Playlist

- [ ] Rewrite the code to use React
- [ ] Make it work. This code is a mess right now.
```

**Comment by rxri** [comment]
Should be fixed with https://github.com/rxri/spicetify-extensions/commit/59c9ef1a10ef2172a1cd16e9e24888253418552a
