### ISSUE TITLE
bug: still getting ads w adblocker :(

### ISSUE THREAD

**Issue by hwilds** [rxri/spicetify-extensions#8]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: newest version? idk how to check
- Spicetify version:2.36.12
```

### 📦 Extension name

adblockify

### 📝 Description

Have adblockify installed, meant to give remove all ads between songs, on the ui and popups, but i still get ads between songs if i play my music through a speaker?

**Comment by rxri** [comment]
Adblockify does not remove ads when you're playing songs via external device (mobile, speakers, smart TVs and so on)
