### ISSUE TITLE
bug: ads popping up

### ISSUE THREAD

**Issue by FortniteFhrer123** [rxri/spicetify-extensions#9]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: most recent
- Spicetify version: 2.36.13
```

### 📦 Extension name

adblockify

### 📝 Description

extension isn't blocked ad anymore, visual ads in ui, nor the ads that pop up in between songs

**Comment by rxri** [comment]
`Most recent` is not a valid answer. I'm pretty sure adblockify did not initialize, that's why you got this error. Please reinstall it from marketplace, or install it manually. I can assure you that it works since I worked on the port for Spicetify v3, and the same code works just fine

**Comment by rxri** [comment]
Issue exists on `1.2.41` and is coming from spicetify

**Comment by FortniteFhrer123** [comment]
yeah reinstalled, no ads anymore, thanks

**Comment by RoverBot-Dev** [comment]
reinstalling extension didnt work for me, i had to update my spicetify and run spicetify apply
